[tool.ruff]
line-length = 100
src = ["lakat"]

[tool.ruff.lint]
select = [
    "A",
    "C4",
    "E",
    "ERA",
    "F",
    "PL",
    "Q",
    "T10",
    "T20",
    "UP",
    "I",
]
ignore = [
    "PLR2004",
]
