[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
skip-magic-trailing-comma = true
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | \.vscode
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
