name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request: {}
  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install
        run: |
          make install-deps
          pip freeze

      - name: lint
        run: make lint
